<?php echo $this->render('./public/header.phtml');?>
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="#">项目管理</a>
   </div>
   <div>
      <ul class="nav navbar-nav">
         <li class="active"><a href="#" class="dropdown-toggle" data-toggle="dropdown">项目管理<b class="caret"></b></a>
            <ul class="dropdown-menu">
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
            </ul>
         </li>
         <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">工具<b class="caret"></b></a>
            <ul class="dropdown-menu">
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
            </ul>
         </li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">文档管理<b class="caret"></b></a>
            <ul class="dropdown-menu">
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
            </ul>
         </li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">人员管理<b class="caret"></b></a>
            <ul class="dropdown-menu">
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
            </ul>
         </li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">权限管理<b class="caret"></b></a>
            <ul class="dropdown-menu">
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
            </ul>
         </li>
      </ul>
      <ul style='margin-right: 20px;' class="nav navbar-nav navbar-right">
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">登录<b class="caret"></b></a>
            <ul class="dropdown-menu">
               <li><a href="#">jmeter</a></li>
               <li><a href="#">EJB</a></li>
               <li><a href="#">Jasper Report</a></li>
               <li class="divider"></li>
               <li><a href="#">分离的链接</a></li>
               <li class="divider"></li>
               <li><a href="#">另一个分离的链接</a></li>
            </ul>
         </li>
      </ul>
   </div>
</nav>

<div class='container-fluid'>
	<div class='row'>
		<div class='col-lg-3'>
                  <div class="panel panel-default">
                  <div class="panel-heading">
                        <h3 class="panel-title">项目列表</h3>
                  </div>
                  <div class="panel-body">圈子开发</div>
                  </div>
		</div>
	</div>
</div>
<?php echo $this->render('./public/footer.phtml');?>

