<?php echo $this->render('./public/header.phtml');?>
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="#">项目管理</a>
   </div>
   <div>
      <ul class="nav navbar-nav">
         <li class="active"><a href="#">项目管理</a></li>
         <li><a href="#">进度管理</a></li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               	接口管理
               <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
               <li class="divider"></li>
               <li><a href="#">测试</a></li>
            </ul>
         </li>
      </ul>
   </div>
</nav>

<div class='container'>
	<div class='row'>
		<div>
		
		</div>
	</div>
</div>
<?php echo $this->render('./public/footer.phtml');?>

