<?php echo $this->render('./public/header.phtml');?>
<?php echo $this->render('./public/nav.phtml');?>

<div class='container-fluid'>
	<div class='row'>
		<div class='col-lg-3'>
                  <div class="panel panel-default">
                  <div class="panel-heading">
                        <h3 class="panel-title">项目列表</h3>
                  </div>
                  <div class="panel-body">圈子开发</div>
                  </div>
		</div>
	</div>
</div>
<?php echo $this->render('./public/footer.phtml');?>

