<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel='stylesheet' type='text/css' href='/lib/css/bootstrap.min.css'>
    <script src="/lib/js/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="/lib/js/bootstrap.min.js"></script>
    <title>bootstarp</title>
</head>
<body>

