<?php echo $this->render('./public/header.phtml');?>
<style type='text/css'>
    .tree{
/* 	   background: #282C34; */
/*     	color: white; */
    }
    .tree,.tree-node,.tree-node-title,.tree-son-node-title{
        width: auto;
    	cursor:pointer;
    }
    .tree-node-title{
        height: 35px;
    	line-height: 24px;
    	padding: 5px;
    	border: 1px solid WhiteSmoke;
    	padding: 5px 5px;
    	background: WhiteSmoke;
    	border-radius: 4px;
    }
    .tree-node-title span{
	    font-size:2.0rem;
    	font-weight: bold;
    }
    .tree-son-node-title span {
	   font-weight: bold;
	   padding: 2px 5px;
    }
    .tree-son-node-title{
        text-indent:2rem;
        height: 28px;
        line-height:38px;
    }
    .tree-node-close .tree-son-node-title{
	    display:none;
    }
    .tree-node-open .tree-son-node-title{
	    display:block;
    }
    .tree-node-open .tree-son-node-title.active{
	    background: LightSkyBlue ;
    }
    .create-node{
	    margin-top: -6px;float: right; font-size:14px;
    }
    .content-menu{
        width: 100px;
        display: none;
    	position: absolute;
    	border: 1px solid WhiteSmoke;
    	border-radius: 4px;
    	background: WhiteSmoke;
    }
    .content-menu p {
	    text-align: center;
        cursor: pointer;
/*     	margin-top: -10px; */
    	height: 35px;
    	line-height: 35px;
    }
    .content-menu p:hover {
	    background: LightSkyBlue ;
    }
    .interface-submit{
	    width: 200px;
    }
	.interface_params, .interface_results{
		width: 100%;
	}
	.interface_params table, .interface_results table{
		width: 100%;
	}
	.interface_params table th, .interface_results table th{
		width: 16.6%;
	}
</style>
<?php echo $this->render('./public/nav.phtml');?>

<div class='container-fluid'>
	<div class='row'>
		<div class='col-lg-3'>
          <div class="panel panel-default">
              <div class="panel-heading">
                    <h3 class="panel-title">项目列表</h3>
              </div>
              <div class="panel-body">
                 <div class='tree'>
                    <?php foreach ($this->project as $pKey => $project) :?>
                    <?php if ($pKey == 0) :?>
                    <div class='tree-node tree-node-open'>
                        <div class='tree-node-title'><span>+</span><?=$project["name"]?><!-- <a class='btn btn-default create-node'>创建</a> --></div>
                        <?php else :?>
                        <div class='tree-node tree-node-close'>
                        <div class='tree-node-title'><span>+</span><?=$project["name"]?></div>
                        <?php endif;?>
                        <?php $count = 0; foreach ($this->interface as $iKey => $interface): $count++?>
                        <?php if ($interface['project_id'] == $project['id'] && $count == 1) :?>
                        <div data-id='<?=$interface['id']?>' class='tree-son-node-title active'><span>─</span><?=$interface["name"]?></div>
                        <?php elseif ($interface['project_id'] == $project['id']):?>
                        <div data-id='<?=$interface['id']?>' class='tree-son-node-title'><span>─</span><?=$interface["name"]?></div>
                        <?php endif;?>
                        <?php endforeach;?>
                    </div>
                    <?php endforeach;?>
                 </div>
              </div>
          </div>
		</div>
		<div class='col-lg-9'>
            <div class='panel panel-default'>
                <div class='panel-heading'>
                    <h3 class='panel-title'>接口详情</h3>
                </div>
                <div class='panel-body'>
                    <form class="form-horizontal" role="form">
<!--                        <div class="form-group"> -->
<!--                          <label class="col-sm-2 control-label">Email</label> -->
<!--                          <div class="col-sm-10"> -->
<!--                            <p class="form-control-static">email@example.com</p> -->
<!--                          </div> -->
<!--                        </div> -->
                        <input type='hidden' value='' name='interfaceId'>
                       <div class="form-group">
                         <label for="inputPassword" class="col-sm-2 control-label">接口名称:</label>
                         <div class="col-sm-10">
                           <input type="text" name='interface_name' class="form-control"  placeholder="请输入接口名称">
                         </div>
                       </div>
                       <div class="form-group">
                         <label for="inputPassword" class="col-sm-2 control-label">接口URL:</label>
                         <div class="col-sm-10">
                           <input type="text" name='interface_url' class="form-control"  placeholder="请输入接口URL">
                         </div>
                       </div>
                       
                       <div class="form-group">
                         <label for="inputPassword" class="col-sm-2 control-label">请求方式:</label>
                         <div class="col-sm-10">
                           <select name='interface_method' style='width: 200px;' class="form-control">
                             <option value="1">GET</option>
                             <option value="2">POST</option>
                             <option value="3">PUT</option>
                             <option value="4">DELETE</option>
                             <option value="5">OPTIONS</option>
                           </select>
                         </div>
                       </div>
                       
                       <div class="form-group">
                         <label for="inputPassword" class="col-sm-2 control-label">接口描述:</label>
                         <div class="col-sm-10">
                           <textarea name='description' class="form-control" rows="4"></textarea>
                         </div>
                       </div>
                       <p style='font-size: 1.5rem; font-weight: bold;'>参数信息填写</p>
                       <div class='interface_params'>
                            <table class='table'>
                                <thead>
                                    <tr>
                                        <th>字段</th>
                                        <th>类型</th>
                                        <th>是否必填</th>
                                        <th>含义</th>
                                        <th>示例</th>
										<th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
								<tfoot>
									<tr><td colspan='6'><a class='btn btn-default add-params-button'>增加参数</a></td></tr>
								</tfoot>
                            </table>
                       </div>
                       
                       <p style='font-size: 1.5rem; font-weight: bold;'>响应信息填写</p>
                       <div class='interface_results'>
                            <table class='table'>
                                <thead>
                                    <tr>
                                        <th>字段</th>
                                        <th>类型</th>
                                        <th>一定存在</th>
                                        <th>含义</th>
                                        <th>示例</th>
										<th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
								<tfoot>
									<tr><td colspan='6'><a class='btn btn-default add-results-button'>增加参数</a></td></tr>
								</tfoot>
                            </table>
                       </div>
                       <div style='text-align: center;'><a class='btn btn-default interface-submit'>提交</a></div>
                     </form>
                </div>
            </div>
		</div>
	</div>
</div>
<div class='content-menu'>
    <p data-type='1'>向上插入一行</p>
    <p data-type='2'>向下插入一行</p>
</div>

<!-- Modal -->

<div class="modal fade" id="dialogForParams" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">请求参数</h4>
      </div>
      <div class="modal-body">
	  <form class="form-horizontal" role="form">
		<div class="form-group">
			<label for="inputPassword" class="col-sm-2 control-label">字段名称:</label>
			<div class="col-sm-10">
			<input type="text" name='fieldName' class="form-control"  placeholder="请输入字段名称">
			</div>
		</div>
		<div class="form-group">
			<label for="inputPassword" class="col-sm-2 control-label">参数类型:</label>
			<div class="col-sm-10">
				<select name='fieldType' style='width: 200px;' class="form-control">
					<option value="1">整型（int）</option>
					<option value="2">浮点型（float）</option>
					<option value="3">字符型（string）</option>
					<option value="4">布尔型（boolean）</option>
					<option value="5">数组（array）</option>
					<option value='6'>对象（object）</option>
				</select>
			</div>
		</div>
		<div class='form-group'>
			<label for="inputPassword" class="col-sm-2 control-label control-label-required">是否必填:</label>
			<label class="radio-inline">
				<input type="radio" name="required" id="inlineRadio1" value="1" checked>是
			</label>
			<label class="radio-inline">
				<input type="radio" name="required" id="inlineRadio2" value="0"> 否
			</label>
		</div>
		<div class="form-group">
			<label for="inputPassword" class="col-sm-2 control-label">含义:</label>
			<div class="col-sm-10">
			<input type="text" name='comment' class="form-control"  placeholder="请输入字段含义">
			</div>
		</div>
		<div class="form-group">
			<label for="inputPassword" class="col-sm-2 control-label">示例:</label>
			<div class="col-sm-10">
				<input type="text" name='case' class="form-control"  placeholder="请输入示例">
			</div>
		</div>
		</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
        <button type="button" class="btn btn-primary confirm-next">确定</button>
      </div>
    </div>
  </div>
</div>


<script type='text/javascript' src='/js/params.js'></script>
<script type="text/javascript">
	var pRows = [];
	var rRows = [];
	$(function() {
		$('.tree-node-title').bind('click', function() {
			if ($(this).parent().filter('.tree-node-open').length) {
				$(this).parent().removeClass('tree-node-open');
				$(this).parent().addClass('tree-node-close');
			} else {
				$(this).parent().addClass('tree-node-open');
				$(this).parent().removeClass('tree-node-close');
				$('.tree-node-open .tree-son-node-title').unbind().bind('click', function() {
					$('.tree-node-open .tree-son-node-title').removeClass('active');
					$(this).addClass('active');
				});
			}
		});
		$('.tree-node-open .tree-son-node-title').bind('click', function() {
			$('.tree-node-open .tree-son-node-title').removeClass('active');
			$(this).addClass('active');
			getParamsAndResults($(this).attr('data-id'));
		});

		$('.add-params-button').bind('click', function(){
			createRows(1);
		});
		$('.add-results-button').bind('click', function(){
			createRows(0);
		});
		$('tr td').bind('mouseup', function(e) {
			var res = $('.content-menu')[0];
			if (e.button !==2 ) {    //如果button=1（鼠标左键），button=2（鼠标右键），button=0（鼠标中间键）
		      	res.style.display = 'none';     //否则不显示div盒子
		    }
		});
		function contentMenuShow(e) 
		{
			var res = $('.content-menu')[0];
			if(e.button === 2){    //如果button=1（鼠标左键），button=2（鼠标右键），button=0（鼠标中间键）
			      res.style.top = e.clientY+'px';   //鼠标点击时给div定位Y轴
			      res.style.left = e.clientX+'px';  //鼠标点击时给div定位X轴
			      res.style.display = 'block';
			      var className = 'content_table';
			      $('tr').removeClass(className);
			      $(this).parent().addClass(className);
			      $('.content-menu').prop('data-ele', className);
			      return false;   //显示div盒子
		    } else {
			      res.style.display = 'none';     //否则不显示div盒子
		    }
		}
		$('tr td').bind('contextmenu', contentMenuShow);
		$('body').on('click', function() {
			$('.content-menu').css('display', 'none');
		});
		$('.content-menu').bind('click', function(e) {
			e = e || window.event;
		    if(e.stopPropagation) { //W3C阻止冒泡方法
		        e.stopPropagation();
		    } else {
		        e.cancelBubble = true; //IE阻止冒泡方法
		    }
		});
		$('.interface-submit').unbind('click').bind('click', function() {
			var name = $('input[name="interface_name"]').val();
			var url = $('input[name="interface_url"]').val();
			var request_method = $('select[name="interface_method"]').val();
			var description = $('textarea[name="description"]').val();
			updateInterface();
// 			$.ajax({
// 				url: '/interface/create',
// 				data: {name: name, url: url, request_method: request_method, description: description},
// 				dataType: 'json',
// 				type: 'post',
// 				success: function(result) {
// 					$('.interface_results').prop('data-interface_id', result.data);
// 					$('.interface_params').prop('data-interface_id', result.data);
// 				},
// 				error: function(err) {
					
// 				}
// 			});
		});
	});
</script>
<?php echo $this->render('./public/footer.phtml');?>